# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

bendo_database: tmp/bendo.sql
bendo_username: username
bendo_password: password
bendo_host: localhost
bendo_adapter: sqlite3
bendo_encoding: utf8
bendo_pool: '5'
bendo_timeout: '5000'
sentry_dsn: 'fakey-mcfake-face'
smtp_host: smtp.gmail.com
smtp_port: '587'
smtp_domain: gmail.com
smtp_authentication_type: plain
smtp_user_name: noreply@nd.edu
smtp_password: emailpwd
smtp_enable_starttls_auto: 'true'
smtp_delivery_method: smtp

development:
  fedora_user: fedoraAdmin
  fedora_password: fedoraAdmin
  fedora_url: http://localhost:8983/fedora
  METRICS_REPORT_RECIPIENT: library@nd.edu
  METRICS_REPORT_SENDER: no-reply@nd.edu
 # sentry_dsn: 'put something here if you want it for testing and change  config.consider_all_requests_local = false'

test:
  fedora_user: fedora
  fedora_password: password
  fedora_url: https://something.com # Keep the fedora_url as this is used as part of VCR tests.
  METRICS_REPORT_RECIPIENT: bogus@bogus.com
  METRICS_REPORT_SENDER: no-reply@nd.edu
  sentry_dsn: 'fakey-mcfake-face'
