name: metrics-ruby-ci

on:
  push:
jobs:
  test-metrics:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install sqlite
      run: sudo apt-get -yqq install sqlite3
    - name: Install sendmail
      run: |
        sudo apt-get -yqq install sendmail
        sudo sendmailconfig
        sudo service sendmail restart
    - name: Install bundler
      run: gem install bundler -v 1.17.3
    - name: Install bundled dependencies
      run: bundle install
    - name: Run tests
      env:
        RAILS_ENV: test
      run: bundle exec rake

